/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.crud.gradebook.stalele1.netbeans.server;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.05 at 04:42:57 PM MST 
//

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="student" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="GrdeItem" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>byte">
 *                           &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "student"
})
@XmlRootElement(name = "Gradebook")
public class Gradebook {

    protected List<Gradebook.Student> student;

    public List<Gradebook.Student> getStudent() {
        if (student == null) {
            student = new ArrayList<Gradebook.Student>();
        }
        return this.student;
    }

    public void setStudent(List<Gradebook.Student> student) {
        this.student = student;
    }       
    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "grdeItem"
    })
    public static class Student {

        @XmlElement(name = "GrdeItem")
        protected List<Gradebook.Student.GrdeItem> grdeItem;
        @XmlAttribute(name = "id")
        protected String id;

        
        public List<Gradebook.Student.GrdeItem> getGrdeItem() {
            if (grdeItem == null) {
                grdeItem = new ArrayList<Gradebook.Student.GrdeItem>();
            }
            return this.grdeItem;
        }
        
        public void setGrdeItem(List<Gradebook.Student.GrdeItem> item) {
                this.grdeItem = item;
        }
        
        public String getId() {
            return id;
        }

        public void setId(String value) {
            this.id = value;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class GrdeItem {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "Name")
            protected String name;
            @XmlAttribute(name = "Weightage")
            protected String weightage;
            @XmlAttribute(name = "Feedback")
            protected String feedback;
            @XmlAttribute(name = "Appeal")
            protected String appeal;

            public String getValue() {
                return value;
            }

            public void setValue(String value) {
                this.value = value;
            }
            public String getAppeal() {
                return appeal;
            }
            public void setAppeal(String value) {
                this.appeal = value;
            }
            public String getName() {
                return name;
            }
            public void setName(String value) {
                this.name = value;
            }
            
            public void setWeightage(String value) {
                this.weightage = value;
            }
            public void setFeedback(String value) {
                this.feedback = value;
            }
            
            public String getWeightage() {
                return weightage;
            }
            public String getFeedback() {
                return feedback ;
            }

        }

    }

}
